services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-amj_doc_db}
      POSTGRES_USER: ${DB_USER:-amj_doc_db_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-m3_f1le_7!}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER:-amj_doc_db_user} -d $${DB_NAME:-amj_doc_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: > 
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0  # Hardcoded Redis URL
      - CELERY_RESULT_BACKEND=redis://redis:6379/0  # Hardcoded Redis URL
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:  # Added Redis dependency
        condition: service_healthy

  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - backend  # Critical fix: Added network attachment
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5

  celery-default:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A auth worker --loglevel=info -Q default --without-gossip --without-heartbeat --without-mingle
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
    networks:
      - backend

  celery-text-processor:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A auth worker --loglevel=info -Q text-processor --without-gossip --without-heartbeat --without-mingle
    env_file:
      - ./backend/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - ./frontend/.env.local
    networks:
      - backend  # Frontend can communicate with backend via this network
    depends_on:
      - backend
  aifastapi:
    build:
      context: ./aifastapi  
      dockerfile: Dockerfile
    command: uvicorn server:app --host 0.0.0.0 --port 8010 --reload
    ports:
      - "8010:8010"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./aifastapi:/app  
    env_file:
      - ./aifastapi/.env  
    depends_on:
      - redis
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
    # Optional IPAM configuration for subnet control
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  postgres_data: