# Generated by Django 5.1.7 on 2025-03-28 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('embedding_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='users.chunk')),
            ],
        ),
    ]
