# Generated by Django 4.2.12 on 2025-04-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='s3_uri',
            field=models.URLField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
