# Generated by Django 4.2.12 on 2025-04-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_file_s3_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='cdn_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
