# Generated by Django 4.2.12 on 2025-05-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_file_cdn_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, max_length=255)),
                ('chunk_text', models.TextField()),
                ('chunk_number', models.IntegerField()),
                ('vector_id', models.CharField(blank=True, max_length=255, null=True)),
                ('model_used', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['file_hash', 'chunk_number'],
                'unique_together': {('file_hash', 'chunk_number')},
            },
        ),
        migrations.RemoveField(
            model_name='embedding',
            name='chunk',
        ),
        migrations.DeleteModel(
            name='Chunk',
        ),
        migrations.DeleteModel(
            name='Embedding',
        ),
    ]
