name: Build and Deploy with Compose

on:
  push:
    branches: [main]

env:
  DOCKERHUB_USER: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['backend', 'frontend', 'aifastapi'] # Add your services
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push
        run: |
          cd ${{ matrix.service }}
          docker build -t $DOCKERHUB_USER/${{ matrix.service }}:latest .
          docker push $DOCKERHUB_USER/${{ matrix.service }}:latest
